### ISSUE TITLE
Nova idéia para "Materiais em Inglês"

### ISSUE THREAD

**Issue by FeFortti** [beatrizmilz/materiais_estudo_R#2]
Material do 1o curso do "Programa de cursos integrados Statistics with R"
Link: https://pt.coursera.org/specializations/statistics
Nível: iniciante (informação do programa)
Habilidades a serem adquiridas: Bayesian Statistics, Linear Regression, Statistical Inference, R Programming
Tempo para conclusão: Aproximadamente 7 meses, sendo sugeridas 5 horas/semana de dedicação ao curso.
1o curso: Introduction to Probability and Data
2o curso: Inferential Statistics
3o curso: Linear Regression and Modeling
4o curso: Bayesian Statistics
5o curso: Statistics with R Capstone
Livro base do 1o curso, disponível gratuitamente em ("read free sample"): https://leanpub.com/openintro-statistics

**Comment by beatrizmilz** [comment]
Adicionei a sugestão! Obrigada!!

**Comment by FeFortti** [comment]
Show! :)
