### ISSUE TITLE
Materiais em espanhol

### ISSUE THREAD

**Issue by gabrielvazdemelo** [beatrizmilz/materiais_estudo_R#20]
@beatrizmilz, tenho um ou outro material em espanhol e que são ótimos. Será que rolaria de inserir? Se sim, onde seria mais adequado? Na lista de português colocando idioma espanhol ou criar uma lista só para espanhol?

**Comment by beatrizmilz** [comment]
Gabriel, boa ideia! Adicionei mas só coloquei um material para nao ficar vazio. Pode fazer contribuicoes no arquivo dados.csv mesmo, e aí na última coluna coloca o idioma como Espanhol. Obrigada!

https://github.com/beatrizmilz/materiais_estudo_R/commit/04c1d90aedd99aed29e4b8a670905264bfb00c1a

**Comment by beatrizmilz** [comment]
Já está online: https://materiais-estudo-r.netlify.app/espanhol.html

**Comment by beatrizmilz** [comment]
Aliás quando for adicionar, aproveita e ja adiciona seu blog :D

**Comment by gabrielvazdemelo** [comment]
Rs, lá não tem muita coisa. Pretendo criar mais conteúdos em breve, aí incluo lá.

**Comment by beatrizmilz** [comment]
Quando se sentir a vontade, adiciona então :) Mas pode ser com pouco conteúdo também hahah

**Comment by beatrizmilz** [comment]
Vou fechar a issue pois essa sugestão foi implementada, ok?
